# my global config
global:
  scrape_interval:     5s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'back1'
    static_configs:
      - targets: ['165.22.26.252:9090'] # , '165.22.26.252:9100']

  - job_name: 'back2'
    static_configs:
      - targets: ['165.22.18.207:9090'] # , '165.22.18.207:9100']

  - job_name: 'back3'
    static_configs:
      - targets: ['104.248.250.52:9090'] #, '104.248.250.52:9100']

