[providers]
  [providers.file]
    filename = "/etc/traefik/traefik.toml"
    watch = true

[api]
  insecure = true
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[http]
  [http.routers]
    [http.routers.router0]
      entryPoints = ["web"]
      middlewares = ["add-api-prefix"]
      service = "testapi"
      rule = "Method(`GET`, `POST`)"

  [http.middlewares]
    [http.middlewares.add-api-prefix.addPrefix]
      prefix = "/api"
    [http.services]
      [http.services.testapi]
        [http.services.testapi.loadBalancer]
          [[http.services.testapi.loadBalancer.servers]]
            url = "http://104.197.153.254:9090"
          [[http.services.testapi.loadBalancer.servers]]
            url = "http://34.70.55.192:9090"
          [[http.services.testapi.loadBalancer.servers]]
            url = "http://34.68.181.57:9090"
